### ISSUE TITLE
Inkscape V1.2

### ISSUE THREAD

**Issue by bdgrichards** [speleo3/inkscape-speleo#10]
## I believe this extension may be breaking with Inkscape v1.2

I tried to install this with v1.2 and couldn't save files to .th2 and could not open .th2 files. Downgrading to Inkscape v1.1 fixed the problem for me, but specifically I was seeing this error in both saving and opening files in v1.2:

![289074640_1699400517110461_7846349782503688065_n](https://user-images.githubusercontent.com/63878587/175812453-361763fb-d6fc-4f92-ba92-2ffafde8e9d8.png)

I tried to dig into the problem a little and I'm not 100% what's causing this, but I suspect it's to do with v1.2 removing deprecated fields, which I presume include `InkOption`. When I manually polyfilled the missing `InkOption`, subsequent inkex attributes could not be found. 

It is also mentioned that some pre v1.0 extension support has been removed in v1.2 in the [changelog](https://inkscape.gitlab.io/extensions/documentation/authors/update1.2.html#other-deprecations-to-inkex)

Hope this helps!

**Comment by bdgrichards** [comment]
Also I should add that I'm using an M1 Mac, in case that's affecting this issue.

**Comment by speleo3** [comment]
Thanks for the report, should be fixed now. M1 Mac doesn't affect this. The reason was removal of `inkex.InkOption` in https://gitlab.com/inkscape/extensions/-/merge_requests/419/diffs?commit_id=da07eab273afafeb3c3adde6b65e1737a4add797

**Comment by bdgrichards** [comment]
All working for me on v1.2 as well - thanks for such a fast fix!
