### ISSUE TITLE
When setting properties of a station a stroke style is added to several objects

### ISSUE THREAD

**Issue by rsevero** [speleo3/inkscape-speleo#15]
Just trying Therion extension for Inkscape, following these instructions (https://therion.speleo.sk/wiki/_media/conversion_of_svg_file_to_therion_format.pdf).

On step 10, when I click on _Apply_ for the first time, my station is redraw with a different style (which is fine) but tons of other objects in my drawing have a stroke added (which is not fine). Is this a bug?

If I uncheck "Drop style" there are no visible changes in my drawing, just the relevant object properties are applied. Can I proceed with "Drop style" unchecked?

**Comment by speleo3** [comment]
Yes you can proceed with "Drop style" unchecked. When exporting to `th2` format, only the properties are relevant, not the style.

Currently, a global `<style>` tag is inserted into the SVG which styles all `<path>` elements. I see that this is not the best solution, the styling should be specific to the selected elements.
